<?php
/**
 * Shared demo roster for presentation uploads (ACCESS campus).
 * Used by tools/build_demo_package.php — keep scholar names in sync with COR/COG filenames.
 */
return [
    'campus' => 'ACCESS',
    'school_year' => '2024-2025',
    'academic_year' => '2024-2025',
    'semester' => '1st Semester',
    'file_groups' => [
        'registrar' => 'DEMO PRESENT | Registrar ACCESS SY 2024-2025',
        'tdp' => 'DEMO PRESENT | TDP ACCESS SY 2024-2025',
        'tes' => 'DEMO PRESENT | TES ACCESS SY 2024-2025',
        'cor' => 'DEMO PRESENT | COR ACCESS SY 2024-2025',
        'cog' => 'DEMO PRESENT | COG ACCESS SY 2024-2025',
        'annex7' => 'DEMO PRESENT | Annex7 ACCESS',
        'billing' => 'DEMO PRESENT | Billing ACCESS SY 2024-2025',
    ],
    'scholars' => [
        [
            'seq' => 'P001',
            'app_no' => 'APP-PRESENT-001',
            'award_no' => 'AWD-PRESENT-001',
            'lastname' => 'REYES',
            'firstname' => 'MARIA',
            'middlename' => 'SANTOS',
            'extname' => '',
            'sex' => 'F',
            'birthdate' => '2002-03-15',
            'course' => 'Bachelor of Science in Information Technology',
            'year_level' => '2',
            'units' => '21',
            'status' => 'Enrolled',
            'remarks' => 'DEMO — presentation scholar 1',
            'id_number' => 'ACCESS-P001',
            'contact' => '09170000001',
            'batch_no' => 'TES-BATCH-2024',
        ],
        [
            'seq' => 'P002',
            'app_no' => 'APP-PRESENT-002',
            'award_no' => 'AWD-PRESENT-002',
            'lastname' => 'DELA CRUZ',
            'firstname' => 'JUAN',
            'middlename' => 'TORRES',
            'extname' => '',
            'sex' => 'M',
            'birthdate' => '2001-07-22',
            'course' => 'Bachelor of Science in Computer Science',
            'year_level' => '3',
            'units' => '18',
            'status' => 'Enrolled',
            'remarks' => 'DEMO — presentation scholar 2',
            'id_number' => 'ACCESS-P002',
            'contact' => '09170000002',
            'batch_no' => 'TES-BATCH-2024',
        ],
        [
            'seq' => 'P003',
            'app_no' => 'APP-PRESENT-003',
            'award_no' => 'AWD-PRESENT-003',
            'lastname' => 'GARCIA',
            'firstname' => 'SOPHIA',
            'middlename' => 'MENDOZA',
            'extname' => '',
            'sex' => 'F',
            'birthdate' => '2003-01-08',
            'course' => 'Bachelor of Science in Nursing',
            'year_level' => '1',
            'units' => '24',
            'status' => 'Enrolled',
            'remarks' => 'DEMO — presentation scholar 3',
            'id_number' => 'ACCESS-P003',
            'contact' => '09170000003',
            'batch_no' => 'TES-BATCH-2025',
        ],
        [
            'seq' => 'P004',
            'app_no' => 'APP-PRESENT-004',
            'award_no' => 'AWD-PRESENT-004',
            'lastname' => 'BAUTISTA',
            'firstname' => 'CARLO',
            'middlename' => 'AQUINO',
            'extname' => 'JR',
            'sex' => 'M',
            'birthdate' => '2000-11-30',
            'course' => 'Bachelor of Science in Criminology',
            'year_level' => '4',
            'units' => '15',
            'status' => 'Enrolled',
            'remarks' => 'DEMO — presentation scholar 4',
            'id_number' => 'ACCESS-P004',
            'contact' => '09170000004',
            'batch_no' => 'TES-BATCH-2025',
        ],
        [
            'seq' => 'P005',
            'app_no' => 'APP-PRESENT-005',
            'award_no' => 'AWD-PRESENT-005',
            'lastname' => 'FERNANDEZ',
            'firstname' => 'ANALYN',
            'middlename' => 'CASTILLO',
            'extname' => '',
            'sex' => 'F',
            'birthdate' => '2002-05-18',
            'course' => 'Bachelor of Elementary Education',
            'year_level' => '2',
            'units' => '21',
            'status' => 'Not Enrolled',
            'remarks' => 'DEMO — validation edge case (not enrolled)',
            'id_number' => 'ACCESS-P005',
            'contact' => '09170000005',
            'batch_no' => 'TES-BATCH-2024',
        ],
    ],
];
